name: Tests

on: [push, pull_request]

env:
  RELEASE: 0
  artifact: 0
  
jobs:
  windows_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@722adc6
      - name: Windows Defender
        run: ci/actions/windows/disable_windows_defender.ps1
      - name: Checkout Submodules
        run: git submodule update --init --recursive
      - name: Fetch Deps
        run: ci/actions/windows/install_deps.ps1
      - name: Run Tests
        run: ci/actions/windows/build.ps1
